### ISSUE TITLE
Run against Ollama Backend?

### ISSUE THREAD

**Issue by AidanNelson** [huggingface/meshgen#12]
Hi @dylanebert --

Thanks for putting this out!  

I already have access to an Ollama server running on a headless GPU machine, so I made some edits to run this against that machine instead of using the internal `llamacpp.py` inference setup.  Would you like a PR for this?   I think it could be an option in preferences to run against a remote Ollama server(along with options for host / port).

Here are some initial outputs:

_"A Sphere"_
<img width="668" alt="Sphere in Blender software" src="https://github.com/user-attachments/assets/9a64f48a-1466-4a95-8852-4643bc0926c1">

_"A Pyramid"_
<img width="681" alt="Pyramid shape in Blender software" src="https://github.com/user-attachments/assets/374cd54d-8fdd-434f-b1c1-c4d3cf089e33">

_"A Cube"_
<img width="686" alt="Screenshot 2024-12-06 at 1 14 47 PM" src="https://github.com/user-attachments/assets/1e286096-9695-45de-b50e-4cfe037e0ccf">

_Also "A Cube"_ 
<img width="741" alt="Screenshot 2024-12-06 at 1 14 40 PM" src="https://github.com/user-attachments/assets/ca993947-20c8-4a94-abb7-b3333529d6bf">

_"A Camera"_
<img width="637" alt="Screenshot 2024-12-06 at 1 23 58 PM" src="https://github.com/user-attachments/assets/5af3f4cf-f223-4b87-8f23-3840b8e4eaed">

Thanks,
Aidan

**Comment by dylanebert** [comment]
Sounds great! My goal is to make installation as easy as possible for people without ML experience, so as long as it's structured to not overwhelm new users, it sounds good to me (i.e. maybe in `Show Developer Options`)

**Comment by dylanebert** [comment]
Merged :)
