### ISSUE TITLE
Failed to load generator: Shared library with base name 'llama' not found

### ISSUE THREAD

**Issue by vuaieo** [huggingface/meshgen#14]
hi so downlaoded and installed the meshgen-cuda.zip on blender 4.2.4 , blender 4.3 and latest compiled build of UPBGE 4.4 but every version it gives same error messege when clicking on load generator: 
i am on linux fedora based distro.

Loading generator...
Failed to load generator: Shared library with base name 'llama' not found
Traceback (most recent call last):
  File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/generator/generator.py", line 72, in load_generator
    import llama_cpp
  File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/__init__.py", line 1, in <module>
    from .llama_cpp import *
  File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 88, in <module>
    _lib = _load_shared_library(_lib_base_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 79, in _load_shared_library
    raise FileNotFoundError(
FileNotFoundError: Shared library with base name 'llama' not found

**Comment by JackHeathcote** [comment]
Bump

**Comment by JackHeathcote** [comment]
Fixed this issue. You need to install: 
1). Visual Studio (might not be needed, but CUDA 12.1 prompted I install this first)
2). NVIDIA CUDA 12.1 
3). This Add-on

**Comment by Rhysjosmin** [comment]
im using the cpu version , im getting the same error

**Comment by zosman1** [comment]
@Rhysjosmin I reproduced your issue on Linux, made a small change to have the builds be run on multiple architectures to support mac/linux/win

Opened a PR with #15 that resolves it on my machine, give it a try and let me know!

**Comment by vuaieo** [comment]
hi @zosman1 i downloaded the [[zosman1:main](https://github.com/zosman1/meshgen/tree/main) zip](https://github.com/zosman1/meshgen/archive/refs/heads/main.zip) and installed but i getting error when clicking on install dependencies, not sure if i did error or so but here is the blender console error:

Python include dir: /home/vuaieo/Desktop/UPBGE_13_12_2024/4.4/python/include/python3.11
Can't access include dir, skipping
ERROR: Could not open requirements file: [Errno 2] No such file or directory: './requirements/cpu.txt'
Traceback (most recent call last):
  File "/home/vuaieo/.config/upbge/4.4/scripts/addons/meshgen-main/operators/install_dependencies.py", line 141, in execute
    install_and_load_dependencies()
  File "/home/vuaieo/.config/upbge/4.4/scripts/addons/meshgen-main/operators/install_dependencies.py", line 112, in install_and_load_dependencies
    subprocess.run(
  File "/home/vuaieo/Desktop/UPBGE_13_12_2024/4.4/python/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/vuaieo/Desktop/UPBGE_13_12_2024/4.4/python/bin/python3.11', '-m', 'pip', 'install', '-r', './requirements/cpu.txt', '--upgrade', '--no-cache-dir', '--target', '/home/vuaieo/.config/upbge/4.4/scripts/addons/meshgen-main/.python_dependencies']' returned non-zero exit status 1.
Error: Python: Traceback (most recent call last):
  File "/home/vuaieo/Desktop/UPBGE_13_12_2024/4.4/python/lib/python3.11/subprocess.py", line 571, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/vuaieo/Desktop/UPBGE_13_12_2024/4.4/python/bin/python3.11', '-m', 'pip', 'install', '-r', './requirements/cpu.txt', '--upgrade', '--no-cache-dir', '--target', '/home/vuaieo/.config/upbge/4.4/scripts/addons/meshgen-main/.python_dependencies']' returned non-zero exit status 1.

**Comment by foleypro** [comment]
Same error here...
> Loading generator... Failed to load generator: Shared library with base name 'llama' not found Traceback (most recent call last): File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/generator/generator.py", line 72, in load_generator import llama_cpp File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/**init**.py", line 1, in from .llama_cpp import * File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 88, in _lib = _load_shared_library(_lib_base_name) ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ File "/home/vuaieo/.config/blender/4.2/scripts/addons/meshgen/.python_dependencies/llama_cpp/llama_cpp.py", line 79, in _load_shared_library raise FileNotFoundError( FileNotFoundError: Shared library with base name 'llama' not found

**Comment by mak448a** [comment]
Hey @vuaieo, I think you may have downloaded the wrong file. I think you may have to download it from https://github.com/zosman1/meshgen/actions/runs/12267123439.

**Comment by zosman1** [comment]
Thanks @mak448a, you are correct, must be downloaded from that action run specifically, the link @vuaieo mentioned is an archive download of the main branch and not a built version of the plugin.

Give it a shot downloading the artifacts from that build and let me know if you still run into any issues with it

**Comment by mak448a** [comment]
Hey @zosman1, I just tried the plugin. It errors when trying to install.
![image](https://github.com/user-attachments/assets/da5795b2-ec8d-4eee-bbe2-f763e58d1f16)
